# Курс «Симулятор SQL»

### **Дашборд "Main info. Users, couriers and orders"**
#### [**Ссылка на Дашборд**](https://redash.public.karpov.courses/dashboards/4633-2_main-info-users-couriers-and-orders)
#### **Главный вопрос** - Динамика основных показателей по пользователям, курьерам и заказам.

### **Структура:**
#### **Количество пользователей и курьеров:**
- [**Динамика новых пользователей и курьеров**](https://redash.public.karpov.courses/queries/64550#98839)
- [**Динамика общего числа пользователей**](https://redash.public.karpov.courses/queries/64550#98840)

#### **Динамика прироста пользователей и курьеров:**  
- [**Динамика прироста числа новых пользователей и курьеров**](https://redash.public.karpov.courses/queries/64550#98854)
- [**Динамика прироста общего числа пользователей и курьеров**](https://redash.public.karpov.courses/queries/64550#98855)

#### **Динамика прироста платящих пользователей и активных курьеров:**    
- [**Динамика платящих пользователей и активных курьеров**](https://redash.public.karpov.courses/queries/64969#99403)
- [**Динамика долей платящих пользователей и активных курьеров**](https://redash.public.karpov.courses/queries/64969#99404)

#### **Доли пользователей по количеству заказов**:    
- [**Доли пользователей с одним и несколькими заказами**](https://redash.public.karpov.courses/queries/64562#99405)

#### **Динамика количества заказов по пользователям**:    
- [**Динамика общего числа заказов, числа первых заказов и числа заказов новых пользователей**](https://redash.public.karpov.courses/queries/65000#99461)
- [**Динамика доли первых заказов и доли заказов новых пользователей в общем числе заказов**](https://redash.public.karpov.courses/queries/65000#99462)

#### **Динамика количества пользователей и заказов на одного курьера**:    
- [**Динамика числа пользователей и заказов на одного курьера**](https://redash.public.karpov.courses/queries/64981#99420)

#### **Среднее время доставки заказа**:    
- [**Динамика среднего времени доставки заказов**](https://redash.public.karpov.courses/queries/64985#99432)

#### **Динамика отмененных заказов к успешым**:    
- [**Динамика показателя cancel rate и числа успешных/отменённых заказов**](https://redash.public.karpov.courses/queries/64999#99444)

### Задача 1.
Для начала давайте проанализируем, насколько быстро растёт аудитория нашего сервиса, и посмотрим на динамику числа пользователей и курьеров. 

**Задание:**

Для каждого дня, представленного в таблицах user_actions и courier_actions, рассчитайте следующие показатели:

Число новых пользователей.
Число новых курьеров.
Общее число пользователей на текущий день.
Общее число курьеров на текущий день.
Колонки с показателями назовите соответственно new_users, new_couriers, total_users, total_couriers. Колонку с датами назовите date. Проследите за тем, чтобы показатели были выражены целыми числами. Результат должен быть отсортирован по возрастанию даты.

**Вариант 1**
```sql
WITH
total_couriers AS ( 
                   SELECT 
                          DISTINCT first_time_courier AS date,
                          COUNT(courier_id) OVER(ORDER BY first_time_courier) AS total_couriers
                     FROM 
                      (SELECT 
                              courier_id,
                              MIN(time::date) AS first_time_courier
                         FROM courier_actions
                        GROUP BY
                              courier_id
                        ORDER BY courier_id) AS t2
                    ORDER BY date
                  ),
total_users AS (
               SELECT 
                      DISTINCT first_time_user AS date,
                      COUNT(user_id) OVER(ORDER BY first_time_user) AS total_users
                 FROM 
                  (SELECT 
                          user_id,
                          MIN(time::date) AS first_time_user
                     FROM user_actions
                    GROUP BY
                          user_id
                    ORDER BY user_id) AS t1
                ORDER BY date
                )
SELECT
       date,
       COALESCE( total_users - LAG(total_users) OVER(ORDER BY date), total_users) AS new_users,
       COALESCE( total_couriers - LAG(total_couriers) OVER(ORDER BY date), total_couriers) AS new_couriers,
       total_users,
       total_couriers
  FROM total_couriers
  LEFT JOIN 
           total_users USING(date)
 ORDER BY
       date
```
**Вариант 2**
```sql
SELECT start_date as date,
       new_users,
       new_couriers,
       (sum(new_users) OVER (ORDER BY start_date))::int as total_users,
       (sum(new_couriers) OVER (ORDER BY start_date))::int as total_couriers
FROM   (SELECT start_date,
               count(courier_id) as new_couriers
        FROM   (SELECT courier_id,
                       min(time::date) as start_date
                FROM   courier_actions
                GROUP BY courier_id) t1
        GROUP BY start_date) t2
    LEFT JOIN (SELECT start_date,
                      count(user_id) as new_users
               FROM   (SELECT user_id,
                              min(time::date) as start_date
                       FROM   user_actions
                       GROUP BY user_id) t3
               GROUP BY start_date) t4 using (start_date)

### [**Динамика новых пользователей и курьеров. Ссылка на график в Redash**](https://redash.public.karpov.courses/queries/64550#98839)

### [**Динамика общего числа пользователей. Ссылка на график в Redash**](https://redash.public.karpov.courses/queries/64550#98840)

### Задача 2.
Анализируя динамику показателей из предыдущего задания, вы могли заметить, что сравнивать абсолютные значения не очень удобно. Давайте посчитаем динамику показателей в относительных величинах.

**Задание:**

Дополните запрос из предыдущего задания и теперь для каждого дня, представленного в таблицах user_actions и courier_actions, дополнительно рассчитайте следующие показатели:

Прирост числа новых пользователей.
Прирост числа новых курьеров.
Прирост общего числа пользователей.
Прирост общего числа курьеров.
Показатели, рассчитанные на предыдущем шаге, также включите в результирующую таблицу.

Колонки с новыми показателями назовите соответственно new_users_change, new_couriers_change, total_users_growth, total_couriers_growth. Колонку с датами назовите date.

Все показатели прироста считайте в процентах относительно значений в предыдущий день. При расчёте показателей округляйте значения до двух знаков после запятой.

Результирующая таблица должна быть отсортирована по возрастанию даты.

```sql
WITH
total_couriers AS ( 
                   SELECT 
                          DISTINCT first_time_courier AS date,
                          COUNT(courier_id) OVER(ORDER BY first_time_courier) AS total_couriers
                     FROM 
                      (SELECT 
                              courier_id,
                              MIN(time::date) AS first_time_courier
                         FROM courier_actions
                        GROUP BY
                              courier_id
                        ORDER BY courier_id) AS t2
                  ),
total_users AS (
               SELECT 
                      DISTINCT first_time_user AS date,
                      COUNT(user_id) OVER(ORDER BY first_time_user) AS total_users
                 FROM 
                  (SELECT 
                          user_id,
                          MIN(time::date) AS first_time_user
                     FROM user_actions
                    GROUP BY
                          user_id
                    ORDER BY user_id) AS t1
                )
SELECT
      date,
      new_users,
      new_couriers,
      total_users,
      total_couriers,
      ROUND((new_users::decimal - LAG(new_users) OVER(ORDER BY date))
             /LAG(new_users) OVER(ORDER BY date)*100, 2)      AS new_users_change,
      ROUND((new_couriers::decimal - LAG(new_couriers) OVER(ORDER BY date))
             /LAG(new_couriers) OVER(ORDER BY date)*100, 2)   AS new_couriers_change,
      ROUND((total_users::decimal - LAG(total_users) OVER(ORDER BY date))
             /LAG(total_users) OVER(ORDER BY date)*100, 2)    AS total_users_growth,
      ROUND((total_couriers::decimal- LAG(total_couriers) OVER(ORDER BY date))
             /LAG(total_couriers) OVER(ORDER BY date)*100, 2) AS total_couriers_growth
FROM 
    (SELECT
           date,
           COALESCE( total_users - LAG(total_users) OVER(ORDER BY date), total_users) AS new_users,
           COALESCE( total_couriers - LAG(total_couriers) OVER(ORDER BY date), total_couriers) AS new_couriers,
           total_users,
           total_couriers
      FROM total_couriers
      LEFT JOIN 
               total_users USING(date)
    ) AS table1
 ORDER BY
       date

### [**Динамика прироста числа новых пользователей и курьеров. Ссылка на график в Redash**](https://redash.public.karpov.courses/queries/64550#98854)

### [**Динамика прироста общего числа пользователей и курьеров. Ссылка на график в Redash**](https://redash.public.karpov.courses/queries/64550#98855)

### Задача 3.
Теперь предлагаем вам посмотреть на нашу аудиторию немного под другим углом — давайте посчитаем не просто всех пользователей, а именно ту часть, которая оформляет и оплачивает заказы в нашем сервисе. Заодно выясним, какую долю платящие пользователи составляют от их общего числа.

**Задание:**

Для каждого дня, представленного в таблицах user_actions и courier_actions, рассчитайте следующие показатели:

Число платящих пользователей.
Число активных курьеров.
Долю платящих пользователей в общем числе пользователей на текущий день.
Долю активных курьеров в общем числе курьеров на текущий день.
Колонки с показателями назовите соответственно paying_users, active_couriers, paying_users_share, active_couriers_share. Колонку с датами назовите date. Проследите за тем, чтобы абсолютные показатели были выражены целыми числами. Все показатели долей необходимо выразить в процентах. При их расчёте округляйте значения до двух знаков после запятой.

Результат должен быть отсортирован по возрастанию даты.

**Вариант 1**
```sql
WITH
total_couriers AS (-- общее количество курьеров каждый день
                   SELECT DISTINCT 
                          first_time_courier AS date,
                          COUNT(courier_id) OVER(ORDER BY first_time_courier) AS total_couriers
                     FROM 
                         (SELECT  courier_id,
                                  MIN(time::date) AS first_time_courier
                            FROM  courier_actions
                            GROUP BY 
                                  courier_id
                            ORDER BY courier_id) AS t2
                  ), 
total_users AS (-- общее количество пользователей каждый день
                SELECT DISTINCT first_time_user AS date,
                     COUNT(user_id) OVER(ORDER BY first_time_user) AS total_users
                 FROM   (SELECT user_id,
                                MIN(time::date) AS first_time_user
                          FROM  user_actions
                         GROUP BY user_id
                         ORDER BY user_id) AS t1
                  ),
new_users_and_couriers AS (-- таблица с количеством новых пользователей и курьеров каждый день
                            SELECT date,
                                   new_users, -- количество новых пользователей каждый день
                                   new_couriers -- количество новых курьеров каждый день
                            FROM   (SELECT date,
                                           COALESCE(total_users - LAG(total_users) OVER(ORDER BY date),
                                                    total_users) AS new_users,
                                           COALESCE(total_couriers - LAG(total_couriers) OVER(ORDER BY date),
                                                    total_couriers) AS new_couriers
                                      FROM total_couriers
                                      LEFT JOIN total_users using(date)
                                   ) AS table1
                            ORDER BY date
                           ),
preparation_table_users AS ( -- предподготовка для нахождения условия разницы между 
                             -- количеством созднанных и отмененных заказов
                           SELECT 
                                    time::DATE AS date,
                                    user_id,
                                    COUNT(order_id) FILTER(WHERE order_id IN 
                                                    (SELECT order_id 
                                                      FROM user_actions 
                                                      WHERE action = 'create_order'
                                                    ))  AS create_orders,
                                    COUNT(order_id) FILTER(WHERE order_id IN 
                                                    (SELECT order_id 
                                                      FROM user_actions 
                                                      WHERE action = 'cancel_order')) AS cancel_orders
                              FROM user_actions
                              GROUP BY date, user_id
                          ),
preparation_table_couriers AS ( -- предподготовка для нахождения условия разницы между принятыми и доставленными заказами
                           SELECT 
                                    time::DATE AS date,
                                    courier_id,
                                    COUNT(order_id) FILTER(WHERE order_id IN 
                                                                            (SELECT order_id  -- ЗАКАЗ ПРИНЯТ
                                                                              FROM courier_actions 
                                                                              WHERE action = 'accept_order')
                                                            AND order_id NOT IN 
                                                                                (SELECT order_id --И ПОТОМ НЕ ОТМЕНЕН 
                                                                                 FROM   user_actions 
                                                                                 WHERE  action = 'cancel_order'
                                                                                )
                                                           )  AS accept_orders,
                                    COUNT(order_id) FILTER(WHERE order_id IN 
                                                    (SELECT order_id 
                                                      FROM courier_actions 
                                                      WHERE action = 'deliver_order')) AS deliver_orders
                              FROM courier_actions
                              GROUP BY date, courier_id
                          ),
new_paying_users_by_day AS ( -- число платящих пользователей, которые в данный день оформили хотя бы один заказ, 
                             -- который в дальнейшем не был отменен.  - 
                             SELECT 
                                  date,
                                  COALESCE(new_paying_users 
                                            - LAG(new_paying_users) OVER(ORDER BY date)
                                            , new_paying_users) AS paying_users  -- НОВЫЕ платящие пользователи ЗА ДЕНЬ  
                              FROM   
                                    (SELECT
                                            DISTINCT date,
                                            COUNT(user_id) OVER(ORDER BY date) AS new_paying_users
                                      FROM  preparation_table_users
                                      WHERE
                                            create_orders - cancel_orders > 0
                                          ORDER BY date
                                    ) AS query2
                             ORDER BY date
                             ),
active_couriers AS ( -- количество активных курьеров каждый день
                             SELECT 
                                  date,
                                  COALESCE(new_active_couriers 
                                            - LAG(new_active_couriers) OVER(ORDER BY date)
                                            , new_active_couriers) AS active_couriers 
                              FROM   
                                    (SELECT
                                            DISTINCT date,
                                            COUNT(courier_id) OVER(ORDER BY date) AS new_active_couriers
                                      FROM  preparation_table_couriers
                                      WHERE
                                               accept_orders  > 0
                                            OR deliver_orders > 0
                                          ORDER BY date
                                    ) AS query2
                             ORDER BY date
                             )
SELECT
      date,
      paying_users,
      active_couriers,

      ROUND(  paying_users::decimal
            / total_users *100
            , 2) AS paying_users_share,
      
      ROUND(  active_couriers::decimal
            / total_couriers *100
            , 2) AS active_couriers_share
       
 FROM new_paying_users_by_day
      LEFT JOIN active_couriers USING(date)
      LEFT JOIN total_users USING(date)
      LEFT JOIN total_couriers USING(date)
ORDER BY 
      date
```
**Вариант 2**
```sql
SELECT date,
       paying_users,
       active_couriers,
       round(100 * paying_users::decimal / total_users, 2) as paying_users_share,
       round(100 * active_couriers::decimal / total_couriers, 2) as active_couriers_share
FROM   (SELECT start_date as date,
               new_users,
               new_couriers,
               (sum(new_users) OVER (ORDER BY start_date))::int as total_users,
               (sum(new_couriers) OVER (ORDER BY start_date))::int as total_couriers
        FROM   (SELECT start_date,
                       count(courier_id) as new_couriers
                FROM   (SELECT courier_id,
                               min(time::date) as start_date
                        FROM   courier_actions
                        GROUP BY courier_id) t1
                GROUP BY start_date) t2
            LEFT JOIN (SELECT start_date,
                              count(user_id) as new_users
                       FROM   (SELECT user_id,
                                      min(time::date) as start_date
                               FROM   user_actions
                               GROUP BY user_id) t3
                       GROUP BY start_date) t4 using (start_date)) t5
    LEFT JOIN (SELECT time::date as date,
                      count(distinct courier_id) as active_couriers
               FROM   courier_actions
               WHERE  order_id not in (SELECT order_id
                                       FROM   user_actions
                                       WHERE  action = 'cancel_order')
               GROUP BY date) t6 using (date)
    LEFT JOIN (SELECT time::date as date,
                      count(distinct user_id) as paying_users
               FROM   user_actions
               WHERE  order_id not in (SELECT order_id
                                       FROM   user_actions
                                       WHERE  action = 'cancel_order')
               GROUP BY date) t7 using (date)

### [**Динамика платящих пользователей и активных курьеров. Ссылка на график в Redash**](https://redash.public.karpov.courses/queries/64969#99403)

### [**Динамика долей платящих пользователей и активных курьеров. Ссылка на график в Redash**](https://redash.public.karpov.courses/queries/64969#99404)

### Задача 4.
Давайте подробнее остановимся на платящих пользователях, копнём немного глубже и выясним, как много платящих пользователей совершают более одного заказа в день. В конце концов нам важно понимать, как в большинстве своём ведут себя наши пользователи — они заходят в приложение, чтобы сделать всего один заказ, или же наш сервис настолько хорош, что они готовы пользоваться им несколько раз в день.

**Задание:**

Для каждого дня, представленного в таблице user_actions, рассчитайте следующие показатели:

Долю пользователей, сделавших в этот день всего один заказ, в общем количестве платящих пользователей.
Долю пользователей, сделавших в этот день несколько заказов, в общем количестве платящих пользователей.
Колонки с показателями назовите соответственно single_order_users_share, several_orders_users_share. Колонку с датами назовите date. Все показатели с долями необходимо выразить в процентах. При расчёте долей округляйте значения до двух знаков после запятой.

Результат должен быть отсортирован по возрастанию даты.

**Вариант 1**
```SQL
WITH
preparation_table AS (
                           SELECT 
                                    time::DATE AS date,
                                    user_id,
                                    COUNT(order_id) FILTER(WHERE order_id IN 
                                                    (SELECT order_id 
                                                      FROM user_actions 
                                                      WHERE action = 'create_order'
                                                    ))  AS create_orders,
                                    COUNT(order_id) FILTER(WHERE order_id IN 
                                                    (SELECT order_id 
                                                      FROM user_actions 
                                                      WHERE action = 'cancel_order')) AS cancel_orders
                              FROM user_actions
                              GROUP BY date, user_id
                          ),
new_paying_users_by_day AS ( -- число платящих пользователей, которые в данный день оформили хотя бы один заказ, 
                  -- который в дальнейшем не был отменен.  - 
                 SELECT 
                      date,
                      COALESCE(new_paying_users 
                                - LAG(new_paying_users) OVER(ORDER BY date)
                                , new_paying_users) AS new_paying_users_by_day  -- НОВЫЕ платящие пользователи ЗА ДЕНЬ  
                  FROM   
                        (SELECT
                                DISTINCT date,
                                COUNT(user_id) OVER(ORDER BY date) AS new_paying_users
                          FROM  preparation_table
                          WHERE
                                create_orders - cancel_orders > 0
                              ORDER BY date
                        ) AS query2
                 ORDER BY date
                 ),
 single_order_users AS ( -- количество плотящих пользователей С ОДНИМ заказом ЗА ДЕНЬ
                         SELECT 
                              date,
                              COALESCE(new_paying_users 
                                        - LAG(new_paying_users) OVER(ORDER BY date)
                                        , new_paying_users) AS single_order_users
                          FROM   
                                (SELECT
                                        DISTINCT date,
                                        COUNT(user_id) OVER(ORDER BY date) AS new_paying_users
                                  FROM preparation_table
                                     
                                  WHERE
                                      create_orders - cancel_orders = 1
                                      ORDER BY date
                                ) AS query2
                         ORDER BY date
                         ),                             
several_orders_users AS ( -- количество плотящих пользователей С МНОЖЕСТВОМ заказов каджый день
                         SELECT 
                              date,
                              COALESCE(new_paying_users 
                                        - LAG(new_paying_users) OVER(ORDER BY date)
                                        , new_paying_users) AS several_orders_users
                          FROM   
                                (SELECT
                                        DISTINCT date,
                                        COUNT(user_id) OVER(ORDER BY date) AS new_paying_users
                                  FROM preparation_table
                                     
                                  WHERE
                                      create_orders - cancel_orders > 1
                                      ORDER BY date
                                ) AS query2
                         ORDER BY date
                         )          
SELECT
      date,
      ROUND(  single_order_users::decimal
            / new_paying_users_by_day * 100
          , 2) AS single_order_users_share,
      ROUND(  several_orders_users::decimal
            / new_paying_users_by_day * 100
          , 2) AS several_orders_users_share    
 FROM new_paying_users_by_day
      LEFT JOIN single_order_users USING(date)
      LEFT JOIN several_orders_users USING(date)
ORDER BY 
      date

**Вариант 2**
```SQL
SELECT date,
       round(100 * single_order_users::decimal / paying_users,
             2) as single_order_users_share,
       100 - round(100 * single_order_users::decimal / paying_users,
                   2) as several_orders_users_share
FROM   (SELECT time::date as date,
               count(distinct user_id) as paying_users
        FROM   user_actions
        WHERE  order_id not in (SELECT order_id
                                FROM   user_actions
                                WHERE  action = 'cancel_order')
        GROUP BY date) t1
    LEFT JOIN (SELECT date,
                      count(user_id) as single_order_users
               FROM   (SELECT time::date as date,
                              user_id,
                              count(distinct order_id) as user_orders
                       FROM   user_actions
                       WHERE  order_id not in (SELECT order_id
                                               FROM   user_actions
                                               WHERE  action = 'cancel_order')
                       GROUP BY date, user_id having count(distinct order_id) = 1) t2
               GROUP BY date) t3 using (date)
ORDER BY date

### [**Доли пользователей с одним и несколькими заказами. Ссылка на график в Redash**](https://redash.public.karpov.courses/queries/64562#99405)

### * Задача 5.
Продолжим изучать наш сервис и рассчитаем несколько показателей, связанных с заказами.

**Задание:**

Для каждого дня, представленного в таблице user_actions, рассчитайте следующие показатели:

Общее число заказов.
Число первых заказов (заказов, сделанных пользователями впервые).
Число заказов новых пользователей (заказов, сделанных пользователями в тот же день, когда они впервые воспользовались сервисом).
Долю первых заказов в общем числе заказов (долю п.2 в п.1).
Долю заказов новых пользователей в общем числе заказов (долю п.3 в п.1).
Колонки с показателями назовите соответственно orders, first_orders, new_users_orders, first_orders_share, new_users_orders_share. Колонку с датами назовите date. Проследите за тем, чтобы во всех случаях количество заказов было выражено целым числом. Все показатели с долями необходимо выразить в процентах. При расчёте долей округляйте значения до двух знаков после запятой.

Результат должен быть отсортирован по возрастанию даты.

**Вариант 1**
```SQL
WITH 
orders AS (SELECT -- Общее число заказов
                  time::DATE AS date,
                  COUNT(order_id) FILTER(WHERE order_id NOT IN (SELECT order_id 
                                                              FROM user_actions
                                                              WHERE action = 'cancel_order')
                                      ) AS orders
            FROM user_actions
          GROUP BY
                 date
          ORDER BY
                 date
          ),
table_with_first_orders AS ( -- ТАБЛИЦА С ПЕРВЫМИ заказами (заказы, сделанные пользователями впервые)
                             SELECT
                                   date,
                                   COUNT(user_id) AS first_orders 
                             FROM
                                 (SELECT 
                                        user_id,
                                        MIN(time::date) AS date
                                  FROM 
                                        user_actions
                                  WHERE 
                                        order_id IS NOT NULL 
                                        AND order_id NOT IN (
                                                            SELECT order_id 
                                                              FROM user_actions 
                                                             WHERE action = 'cancel_order'
                                                            )
                                  GROUP BY 
                                        user_id
                                  ) AS qwerty2
                             GROUP BY 
                                  date
                             ORDER BY 
                                  date
                            ),
first_order_dates AS (
                        SELECT 
                            user_id,
                            MIN(time::date) AS first_order_date
                        FROM 
                            user_actions
                        WHERE 
                            action = 'create_order'
                        GROUP BY 
                            user_id
                    ),
new_user_orders AS (
                    SELECT 
                          date,
                          COALESCE(new_users_orders, 0) AS new_users_orders
                    FROM
                        (SELECT 
                            f.first_order_date AS date,
                            COUNT(ua.order_id) AS new_users_orders
                        FROM 
                            first_order_dates f
                        LEFT JOIN 
                            user_actions ua ON f.user_id = ua.user_id 
                            AND ua.time::date = f.first_order_date
                            AND ua.order_id NOT IN (SELECT order_id 
                                                      FROM user_actions 
                                                     WHERE action = 'cancel_order')
                        GROUP BY 
                            f.first_order_date
                        ) AS qwerty1
                   ORDER BY 
                        date
                    )
SELECT 
       date,
       orders,
       first_orders,
       new_users_orders,
       ROUND(  first_orders::decimal
             / orders * 100, 2) AS first_orders_share,
       ROUND(  new_users_orders::decimal
             / orders * 100, 2) AS new_users_orders_share
  FROM orders
       LEFT JOIN table_with_first_orders USING(date)
       LEFT JOIN new_user_orders USING(date)
 GROUP BY 
      date, orders, first_orders, new_users_orders
 ORDER BY 
      date
```
**Вариант 2**
```SQL
SELECT date,
       orders,
       first_orders,
       new_users_orders::int,
       round(100 * first_orders::decimal / orders, 2) as first_orders_share,
       round(100 * new_users_orders::decimal / orders, 2) as new_users_orders_share
FROM   (SELECT creation_time::date as date,
               count(distinct order_id) as orders
        FROM   orders
        WHERE  order_id not in (SELECT order_id
                                FROM   user_actions
                                WHERE  action = 'cancel_order')
           and order_id in (SELECT order_id
                         FROM   courier_actions
                         WHERE  action = 'deliver_order')
        GROUP BY date) t5
    LEFT JOIN (SELECT first_order_date as date,
                      count(user_id) as first_orders
               FROM   (SELECT user_id,
                              min(time::date) as first_order_date
                       FROM   user_actions
                       WHERE  order_id not in (SELECT order_id
                                               FROM   user_actions
                                               WHERE  action = 'cancel_order')
                       GROUP BY user_id) t4
               GROUP BY first_order_date) t7 using (date)
    LEFT JOIN (SELECT start_date as date,
                      sum(orders) as new_users_orders
               FROM   (SELECT t1.user_id,
                              t1.start_date,
                              coalesce(t2.orders, 0) as orders
                       FROM   (SELECT user_id,
                                      min(time::date) as start_date
                               FROM   user_actions
                               GROUP BY user_id) t1
                           LEFT JOIN (SELECT user_id,
                                             time::date as date,
                                             count(distinct order_id) as orders
                                      FROM   user_actions
                                      WHERE  order_id not in (SELECT order_id
                                                              FROM   user_actions
                                                              WHERE  action = 'cancel_order')
                                      GROUP BY user_id, date) t2
                               ON t1.user_id = t2.user_id and
                                  t1.start_date = t2.date) t3
               GROUP BY start_date) t6 using (date)
ORDER BY date

### [**Динамика общего числа заказов, числа первых заказов и числа заказов новых пользователей. Ссылка на график в Redash**](https://redash.public.karpov.courses/queries/65000#99461)

### [**Динамика доли первых заказов и доли заказов новых пользователей в общем числе заказов. Ссылка на график в Redash**](https://redash.public.karpov.courses/queries/65000#99462)

### Задача 6.
Теперь давайте попробуем примерно оценить нагрузку на наших курьеров и узнаем, сколько в среднем заказов и пользователей приходится на каждого из них.

**Задание:**

На основе данных в таблицах user_actions, courier_actions и orders для каждого дня рассчитайте следующие показатели:

Число платящих пользователей на одного активного курьера.
Число заказов на одного активного курьера.
Колонки с показателями назовите соответственно users_per_courier и orders_per_courier. Колонку с датами назовите date. При расчёте показателей округляйте значения до двух знаков после запятой.

Результирующая таблица должна быть отсортирована по возрастанию даты.

**Вариант 1**
```sql
WITH
total_couriers AS (-- общее количество курьеров каждый день
                   SELECT DISTINCT 
                          first_time_courier AS date,
                          COUNT(courier_id) OVER(ORDER BY first_time_courier) AS total_couriers
                     FROM 
                         (SELECT  courier_id,
                                  MIN(time::date) AS first_time_courier
                            FROM  courier_actions
                            GROUP BY 
                                  courier_id
                            ORDER BY courier_id) AS t2
                  ), 
total_users AS (-- общее количество пользователей каждый день
                SELECT DISTINCT first_time_user AS date,
                     COUNT(user_id) OVER(ORDER BY first_time_user) AS total_users
                 FROM   (SELECT user_id,
                                MIN(time::date) AS first_time_user
                          FROM  user_actions
                         GROUP BY user_id
                         ORDER BY user_id) AS t1
                  ),
total_orders AS (-- общее количество заказов на день
                SELECT DISTINCT first_time_order AS date,
                     COUNT(order_id) OVER(ORDER BY first_time_order) AS total_orders
                 FROM   (SELECT order_id,
                                MIN(creation_time::date) AS first_time_order
                          FROM  orders
                         GROUP BY order_id
                         ORDER BY order_id) AS t1
                WHERE order_id NOT IN (
                                       SELECT order_id FROM user_actions 
                                       WHERE action = 'cancel_order')
                  ),     
new_orders_by_day AS (--количество новых заказов каждый день
                        SELECT date,
                               new_orders -- количество новых заказов каждый день
                        FROM   (SELECT date,
                                       COALESCE(total_orders - LAG(total_orders) OVER(ORDER BY date),
                                                total_orders) AS new_orders
                                  FROM total_orders
                               ) AS table1
                        ORDER BY date
                       ),
preparation_table_users AS ( -- предподготовка для нахождения условия разницы между 
                             -- количеством созднанных и отмененных заказов
                           SELECT 
                                    time::DATE AS date,
                                    user_id,
                                    COUNT(order_id) FILTER(WHERE order_id IN 
                                                    (SELECT order_id 
                                                      FROM user_actions 
                                                      WHERE action = 'create_order'
                                                    ))  AS create_orders,
                                    COUNT(order_id) FILTER(WHERE order_id IN 
                                                    (SELECT order_id 
                                                      FROM user_actions 
                                                      WHERE action = 'cancel_order')) AS cancel_orders
                              FROM user_actions
                              GROUP BY date, user_id
                          ),
preparation_table_couriers AS ( -- предподготовка для нахождения условия разницы между принятыми и доставленными заказами
                           SELECT 
                                    time::DATE AS date,
                                    courier_id,
                                    COUNT(order_id) FILTER(WHERE order_id IN 
                                                                            (SELECT order_id  -- ЗАКАЗ ПРИНЯТ
                                                                              FROM courier_actions 
                                                                              WHERE action = 'accept_order')
                                                            AND order_id NOT IN 
                                                                                (SELECT order_id --И ПОТОМ НЕ ОТМЕНЕН 
                                                                                 FROM   user_actions 
                                                                                 WHERE  action = 'cancel_order'
                                                                                )
                                                           )  AS accept_orders,
                                    COUNT(order_id) FILTER(WHERE order_id IN 
                                                    (SELECT order_id 
                                                      FROM courier_actions 
                                                      WHERE action = 'deliver_order')) AS deliver_orders
                              FROM courier_actions
                              GROUP BY date, courier_id
                          ),
new_paying_users_by_day AS ( -- число платящих пользователей, которые в данный день оформили хотя бы один заказ, 
                             -- который в дальнейшем не был отменен.  - 
                             SELECT 
                                  date,
                                  COALESCE(new_paying_users 
                                            - LAG(new_paying_users) OVER(ORDER BY date)
                                            , new_paying_users) AS paying_users  -- НОВЫЕ платящие пользователи ЗА ДЕНЬ  
                              FROM   
                                    (SELECT
                                            DISTINCT date,
                                            COUNT(user_id) OVER(ORDER BY date) AS new_paying_users
                                      FROM  preparation_table_users
                                      WHERE
                                            create_orders - cancel_orders > 0
                                          ORDER BY date
                                    ) AS query2
                             ORDER BY date
                             ),
active_couriers AS ( -- количество активных курьеров каждый день
                             SELECT 
                                  date,
                                  COALESCE(new_active_couriers 
                                            - LAG(new_active_couriers) OVER(ORDER BY date)
                                            , new_active_couriers) AS active_couriers 
                              FROM   
                                    (SELECT
                                            DISTINCT date,
                                            COUNT(courier_id) OVER(ORDER BY date) AS new_active_couriers
                                      FROM  preparation_table_couriers
                                      WHERE
                                               accept_orders  > 0
                                            OR deliver_orders > 0
                                          ORDER BY date
                                    ) AS query2
                             ORDER BY date
                             )
SELECT
      date,
      ROUND(  paying_users::decimal
            / active_couriers 
            , 2) AS users_per_courier,
      ROUND(  new_orders::decimal
            / active_couriers
            , 2) AS orders_per_courier
 FROM new_paying_users_by_day
      LEFT JOIN active_couriers USING(date)
      LEFT JOIN new_orders_by_day USING(date)
ORDER BY 
      date
```
**Вариант 2**
```sql
SELECT date,
       round(paying_users::decimal / couriers, 2) as users_per_courier,
       round(orders::decimal / couriers, 2) as orders_per_courier
FROM   (SELECT time::date as date,
               count(distinct courier_id) as couriers
        FROM   courier_actions
        WHERE  order_id not in (SELECT order_id
                                FROM   user_actions
                                WHERE  action = 'cancel_order')
        GROUP BY date) t1 join (SELECT creation_time::date as date,
                               count(distinct order_id) as orders
                        FROM   orders
                        WHERE  order_id not in (SELECT order_id
                                                FROM   user_actions
                                                WHERE  action = 'cancel_order')
                        GROUP BY date) t2 using (date) join (SELECT time::date as date,
                                            count(distinct user_id) as paying_users
                                     FROM   user_actions
                                     WHERE  order_id not in (SELECT order_id
                                                             FROM   user_actions
                                                             WHERE  action = 'cancel_order')
                                     GROUP BY date) t3 using (date)
ORDER BY date

### [**Динамика числа пользователей и заказов на одного курьера. Ссылка на график в Redash**](https://redash.public.karpov.courses/queries/64981#9942062)

### Задача 7.
Давайте рассчитаем ещё один полезный показатель, характеризующий качество работы курьеров.

**Задание:**

На основе данных в таблице courier_actions для каждого дня рассчитайте, за сколько минут в среднем курьеры доставляли свои заказы.

Колонку с показателем назовите minutes_to_deliver. Колонку с датами назовите date. При расчёте среднего времени доставки округляйте количество минут до целых значений. Учитывайте только доставленные заказы, отменённые заказы не учитывайте.

Результирующая таблица должна быть отсортирована по возрастанию даты.

**Вариант 1**
```sql
SELECT 
      date,
      ROUND(extract(epoch FROM 
            (avg(time_diff))) / 60)::integer AS minutes_to_deliver
 FROM
    (SELECT DISTINCT deliver_time_order::date AS date, -- именно день когда заказ доставлен идет в зачет
            AGE(deliver_time_order, first_time_order) AS time_diff
       FROM 
           (SELECT 
                    order_id,
                    MIN(time) AS first_time_order,
                    MAX(time) AS deliver_time_order
              FROM  courier_actions
             GROUP BY 
                    courier_id, order_id
             ORDER BY order_id
            ) AS t1
      WHERE order_id NOT IN (SELECT order_id 
                               FROM user_actions 
                              WHERE action = 'cancel_order')
    ) AS query1
GROUP BY 
      date
ORDER BY 
      date
```
**Вариант 2**
```sql
SELECT date,
       round(avg(delivery_time))::int as minutes_to_deliver
FROM   (SELECT order_id,
               max(time::date) as date,
               extract(epoch
        FROM   max(time) - min(time))/60 as delivery_time
        FROM   courier_actions
        WHERE  order_id not in (SELECT order_id
                                FROM   user_actions
                                WHERE  action = 'cancel_order')
        GROUP BY order_id) t
GROUP BY date
ORDER BY date

### [**Динамика среднего времени доставки заказов. Ссылка на график в Redash**](https://redash.public.karpov.courses/queries/64985#99432)

### Задача 8.
И наконец, давайте оценим почасовую нагрузку на наш сервис, выясним, в какие часы пользователи оформляют больше всего заказов, и заодно проанализируем, как изменяется доля отмен в зависимости от времени оформления заказа.

**Задача:**

На основе данных в таблице orders для каждого часа в сутках рассчитайте следующие показатели:

Число успешных (доставленных) заказов.
Число отменённых заказов.
Долю отменённых заказов в общем числе заказов (cancel rate).
Колонки с показателями назовите соответственно successful_orders, canceled_orders, cancel_rate. Колонку с часом оформления заказа назовите hour. При расчёте доли отменённых заказов округляйте значения до трёх знаков после запятой.

Результирующая таблица должна быть отсортирована по возрастанию колонки с часом оформления заказа.

```SQL
SELECT 
      hour,
      successful_orders,
      canceled_orders,
      ROUND(canceled_orders::decimal /total_orders, 3) AS cancel_rate
FROM
    (SELECT 
          hour,
          COUNT(order_id) FILTER(WHERE order_id IN (SELECT order_id
                                                      FROM courier_actions
                                                     WHERE action = 'deliver_order')
                                 ) AS successful_orders,
          COUNT(order_id) FILTER(WHERE order_id IN (SELECT order_id
                                                      FROM user_actions
                                                     WHERE action = 'cancel_order')
                                 ) AS canceled_orders,
          COUNT(order_id) AS total_orders
      FROM
           (SELECT
                  DATE_PART('hour', creation_time)::integer AS hour,
                  order_id
             FROM orders
            ) AS qwerty1
     GROUP BY
         hour
    ) AS qwerty2
ORDER BY 
      hour

### [**Динамика показателя cancel rate и числа успешных/отменённых заказов. Ссылка на график в Redash**](https://redash.public.karpov.courses/queries/64999#99444)